server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
spring:
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: ${CONFIG_ROOT_PATH}
encrypt:
  key: $(ENCRYPTION_KEY}
